### ISSUE TITLE
Thread safety of M2MResourceBase::set_value

### ISSUE THREAD

**Issue by Alex-EEE** [PelionIoT/mbed-cloud-client#68]
Hi,

So out of the box, mbed-cloud-client forks several threads that can manipulate the underlying data of the published Objects and Resources (that is, those threads can change the underlying values of the Resources if the Lwm2m Server makes a PUT / Write)  

Given that, can you comment on the thread safety of using the various get and set functions inside of M2MResourceBase?  Are the data structures mutexed within the client such that, if the main thread happens to call "set_value" while some event thread happens to be servicing a Lwm2m Write from the network on the same resource, that you won't have a synchronization issue?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTCLT-4380

**Comment by teetak01** [comment]
Hi @Alex-EEE I think this might be valid issue. The values probably could be better protected in case of simultaneous cloud and application access. Have you encountered some issues or is this based on analysis?

**Comment by teetak01** [comment]
There will be some concurrency risks in rare cases, but as the LwM2M is designed to report the latest values, not historical series, I think this is acceptable limitation.
